# Generated by Django 4.2.5 on 2023-09-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Exclusive', 'Entreprise'), ('Premium', 'Pro'), ('Basic', 'Basic')], default='Basic', max_length=30),
        ),
    ]
